language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
cache: apt
sudo: required
dist: trusty
env:
  global:
  - PACKAGE=irmin-watcher
matrix:
  include:
  - env: OCAML_VERSION=4.07
    os: linux
  - env: OCAML_VERSION=4.07
    os: osx
  - env: OCAML_VERSION=4.06
    os: linux
  - env: OCAML_VERSION=4.05
    os: linux
