name: Main workflow

on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
        ocaml-version:
          - 5.1.1
          - 5.1.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}
      - run: opam pin add . --no-action
      - run: opam install . --deps-only --with-doc --with-test
      - run: opam exec -- dune build
      - run: opam exec -- dune runtest
